#!/usr/bin/env python3
"""Generate sim/params.inc from the shared PARAMS dict.

Run from the project root:
    python3 pcb/gen_params.py
"""

import os

# Shared parameters — single source of truth for all SPICE simulations.
# Values must match component values in gen_schematic.py.
PARAMS = {
    # ── Gain stage (gen_schematic.py: R3, R6) ────────────────────────────
    "R3":           "2.2k",   # gain resistor (R3 in schematic)
    "R6_default":   "5.6k",   # feedback resistor, default BOM
    "R6_hi_gain":   "47k",    # feedback resistor, hi-gain BOM variant
    # ── HV bias network ──────────────────────────────────────────────────
    "R_GBIAS":      "100Meg", # single HV bias resistor (R_GBIAS in schematic, 100MΩ 200V)
    "R_BIAS1":      "100Meg", # bootstrapped bias resistor
    # ── Capsule model (customer-supplied; nominal for simulation) ─────────
    "Cc":           "55p",    # capsule self-capacitance (typical LDC capsule)
    "C8":           "10n",    # input coupling cap (C8 in schematic)
    # ── Output stage ─────────────────────────────────────────────────────
    "C_DC":         "4.7u",   # DC block cap (C7 in schematic)
    # ── Charge pump (gen_schematic.py: Cp1/Cp2/Cp3, Cres1, L1, C9) ──────
    "Cp":           "100n",   # pump capacitors (Cp1, Cp2, Cp3)
    "Cres":         "470n",   # reservoir cap (Cres1)
    "L1_val":       "10m",    # HV filter inductor value (10 mH)
    "L1_DCR":       "8",      # L1 winding resistance Ω (FNR5040S datasheet)
    "C_LC":         "470n",   # HV filter cap (C9 in schematic)
    # ── Supply voltages ───────────────────────────────────────────────────
    "V_OPA":        "24",     # regulated supply (Z_REG1 = 24V BZT52C24)
    "V_OSC":        "15",     # oscillator rail (Z_OSC1 = 15V MMSZ15VT1G)
    "V_HV_clamp":   "68",     # HV boost clamp (DZ1 = 68V BZX55C68)
    "V_MID":        "12",     # V_OPA/2 midpoint (R4/R5 divider)
    # ── OPA1641 behavioral model (from datasheet) ─────────────────────────
    "OPA_OL_GAIN":  "100k",   # open-loop gain (100 dB)
    "OPA_VN_REQ":   "377",    # voltage noise equiv. resistor (2.5 nV/√Hz → 377 Ω)
}

_OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "sim", "params.inc")


def main():
    lines = [
        "* sim/params.inc — generated by pcb/gen_params.py; do not edit by hand",
        "* Source of truth: pcb/gen_params.py  (values must match gen_schematic.py)",
        "*",
    ]
    for key, val in PARAMS.items():
        lines.append(f".param {key:<16} = {val}")

    out = os.path.normpath(_OUT)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(PARAMS)} params)")


if __name__ == "__main__":
    main()
